CREATE TABLE public.carrera  ( 
	id                  	int4 NOT NULL DEFAULT nextval('carrera_id_seq'::regclass),
	nombre              	varchar(80) NOT NULL,
	modalidades         	varchar(50) NOT NULL,
	provincia           	varchar(80) NOT NULL,
	ciudad              	varchar(80) NOT NULL,
	direccion           	varchar(200) NULL,
	fecha_inicio        	timestamp NULL,
	descripcion         	text NULL,
	url_web             	varchar(500) NULL,
	recomendada         	bool NULL,
	url_imagen          	varchar(500) NULL,
	distancia_disponible	varchar(50) NULL 
	)
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(145, 'El Cruce Columbia', 'Equipos;Individual', 'Río Negro', 'Bariloche', '', '2015-02-05 00:00:00.0', 'El objetivo de la carrera es cruzar los Andes, uniendo Argentina y Chile, en una distancia de más de 100 kms, divididos en 3 etapas. Dado que la Cordillera de los Andes ofrece muchísimos pasos por donde unir ambos países, el recorrido cambia todos los años, manteniendo siempre marcos geográficos únicos en el mundo.', 'http://elcrucecolumbia.com/', false, 'http://clubdecorredores.com/carreras/2015/c394/logo.jpg', '100')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(146, 'Carrera UNICEF por la educación', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Figueroa Alcorta y Dorrego', '2015-03-15 00:00:00.0', '', 'http://clubdecorredores.com/carreras/calle/630/Carrera-UNICEF-por-la-educaci-n/2485/', false, 'http://clubdecorredores.com/carreras/2015/c446/logo.jpg', '2/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(147, 'Terma Adventure Race - Tandil', 'Equipos; Individual', 'Buenos Aires', 'Tandil', '', '2015-03-15 00:00:00.0', 'Ya estamos trabajando para la 16ta. edición de la fecha apertura del circuito de aventuras más convocante del país. TANDIL recibirá, como cada año, a los miles de corredores de todo el país que harán de esta competencia una hermosa aventura para disfrutar con familia y amigos en una de las ciudades turísticas más importantes de la República Argentina, con todas las comodidades para vivir un fin de semana inolvidable.', 'http://clubdecorredores.com/carreras/aventura/618/Terma-Adventure-Race/2479/', false, 'http://clubdecorredores.com/carreras/2015/c370/logo-adventure-race.jpg', '25')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(148, 'TNF Endurance Challenge San Martin de los Andes', 'Individual', 'Neuquen', 'San Martin de los Andes', '', '2015-03-22 00:00:00.0', '', 'http://endurancechallengeargentina.com/', false, 'http://clubdecorredores.com/carreras/2015/c411/logo.jpg', '10/21/50/80')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(149, 'La Carrera de Miguel', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Miguel Sánchez (ex Av. Crisólogo Larralde) y Padre Canavery (frente al CENARD)', '2015-03-22 00:00:00.0', 'La tradicional Carrera de Miguel, competencia que se realiza en homenaje a Miguel Sánchez, atleta desaparecido en 1978 durante la última dictadura militar.', 'http://clubdecorredores.com/carreras/calle/634/La-Carrera-de-Miguel/2488/', false, 'http://clubdecorredores.com/carreras/2015/c385/logo.jpg', '3/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(150, 'Fila Race', 'Individual', 'Capital Federal', 'Capital Federal', 'Puerto Madero', '2015-04-19 00:00:00.0', 'La 6ta. edición de FILA RACE se llevará a cabo el domingo 19 de abril a las 8.30 horas en Puerto Madero, desde el Parque Micaela Bastidas, con una distancia de 10km competitivos y un nuevo recorrido. El mismo recorre las calles típicas y los edificios históricas de la zona, logrando un renovado circuito para este 2015. El año pasado, reunimos diez mil corredores que crearon una atmósfera increíble durante una mañana de sol en Buenos Aires.', 'http://www.fila.com.ar/race/', false, 'http://clubdecorredores.com/carreras/2015/c372/logo.jpg', '10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(151, 'Maratón Héroes de Malvinas', 'Individual', 'Buenos Aires', 'Costanera Sur', '', '2015-05-03 00:00:00.0', 'Con  motivo  de  los  33º  ANIVERSARIO  DE  LA  GESTA DE  MALVINAS  Y  EL  BAUTISMO DE FUEGO DE LA FUERZA AEREA ARGENTINA, esta Institución se encuentra abocada en  la  organización  de  una  carrera  de  calle. Buscamos  a  través  de  este  evento  acrecentar  los  lazos  de  amistad  entre  nuestra 
Institución y la comunidad, recordando a nuestros “55 Héroes de Malvinas” y manteniendo viva nuestra historia.', 'http://clubdecorredores.com/carreras/calle/637/Marat-n-H-roes-de-Malvinas/', false, 'http://clubdecorredores.com/carreras/2015/c449/logo.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(152, 'Raid Columbia', 'Equipos; Individual', 'Salta y Jujuy', 'Salta y Jujuy', '', '2015-05-08 00:00:00.0', 'Llega el Raid Columbia 2015. Luego de vivir una experiencia unica en el 2014, transitando por la maravillosa geografia de salta y jujuy por caminos cargados por naturaleza y cultura. Seguimos trabajando para que el 2015 el RAID los sorprenda La ruta del Tren a las nubes, el imponente cerro de Siete Colores uniendo Tumbaya y Purmamarca y la inmensidad del desierto de sal que ofrece Salinas Grandes, serán los escenarios de El Raid Columbia 2015.
Serán tres días de recorrido uniendo Salta y Jujuy, dónde podrán participar en equipos de dos participantes e individuales.
Los invitamos a experimentar la sensación de correr en altura, a más de 3200 msnm, de conocer las comunidades, la cultura ancestral y la magia de la naturaleza que ofrece el Norte Argentino.', 'http://raidandes.com/', false, 'http://clubdecorredores.com/carreras/2015/c367/logo.jpg', '60')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(153, 'Star Wars Run Night Edition', 'Individual', 'Capital Federal', 'Capital Federal', 'Hipódromo de Palermo', '2015-05-08 00:00:00.0', '', 'http://clubdecorredores.com/carreras/calle/640/Star-Wars-Run-Night-Edition/2503/', false, 'http://clubdecorredores.com/carreras/2015/c452/logo.jpg', '7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(154, 'Fiestas Mayas', 'Individual', 'Capital Federal', 'Capital Federal', 'Figueroa Alcorta y Monroe', '2015-05-25 00:00:00.0', 'Festejemos el 25 de mayo formando parte de la carrera más tradicional de Argentina.', 'http://fiestasmayasjumbo.com/info.html', false, 'http://clubdecorredores.com/carreras/2015/c451/logo.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(155, 'Maratón Ejército 2015', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Del Libertador y Dorrego', '2015-05-31 00:00:00.0', '', 'http://clubdecorredores.com/carreras/calle/636/Marat-n-Ej-rcito-2015/2495/', false, 'http://clubdecorredores.com/carreras/2015/c441/logo.jpg', '4/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(156, 'We Run BUE  21K', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Figueroa Alcorta y Dorrego', '2015-06-07 00:00:00.0', 'El objetivo de correr 21km solo te lo pones una vez. Despues ya no te alcanza con llegar. Bajar tu propia marca es lo que transforma una carrera en algo memorable. Superarte es la verdadera razón por la que haces todo esto. Sabes que para obtener algo, hay que sacrificar algo. Para lograr mas, hay que poner mas. Tenes que llegar a tu límite y pedirte un extra que convierta un instante de euforia en un recuerdo eterno. Ante la pregunta "¿Puedo dar mas?", la respuesta es siempre Sí. Pedite Mas.', 'http://www.nike.com/ar/es_ar/c/running/we-run-bue', false, 'http://clubdecorredores.com/carreras/2015/c447/logo.jpg', '21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(157, 'Leds Run', 'Individual', 'Buenos Aires', 'Canning', 'Barrio La Alameda F.Casares y Ruta 58', '2015-06-13 00:00:00.0', 'Leds Run es una nueva experiencia de running, luces y música. 5K nocturnos donde vas a correr "lookeado" con luces y pinturas fluorescente, en un circuito ambientado con luces y fuego. Para terminar en una fiesta con DJ en Vivo', 'http://www.ledsrun.org/', false, 'http://www.yocorro.com.ar/media/k2/items/cache/3bd6583af5a14653b7b54db2c9fe7f3e_L.jpg', '5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(158, '5° Maraton Hispano Argentina', 'Individual', 'Buenos Aires', 'Costanera Sur', '', '2015-06-21 00:00:00.0', 'Conocé una carrera diferente, música en vivo, comida tradicional y sorteos. No se suspende por lluvia.', 'http://clubdecorredores.com/carreras/calle/644/Marat-n-Hispano-Argentino-2015/2523/', false, 'http://clubdecorredores.com/carreras/2015/c453/logo.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(174, '42K de Buenos Aires', 'Individual', 'Capital Federal', 'Capital Federal', 'Av Libertador y Sarmiento', '2015-10-11 00:00:00.0', 'En este 2015 la Maratón de Buenos Aires tendrá un nuevo recorrido, la largada será en Av. Libertador y Sarmiento, el día 11 de octubre.', 'http://sigmasecurepay.info/events/42k-maraton-de-buenos-aires-2015-42km/', true, 'http://www.yocorro.com.ar/media/k2/items/cache/79e08f32fa8a036f84441baab7b7a7ff_L.jpg', '42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(175, 'Carrera Verde', 'Individual;Kids', 'Capital Federal', 'Capital Federal', 'Figueroa Alcorta y Monroe', '2015-09-20 00:00:00.0', 'Corremos y ayudamos a crear Conciencia Verde para hacer de nuestra ciudad, una Ciudad más Linda, más VERDE para Vivir!', 'http://www.carreraverde.org/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/11053512_374815459395170_2128037578395830311_n.jpg?oh=32ecb24e6747c527507eed8ae28962e4&oe=56103108', '2/7/12')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(159, 'Terma Adventure Race - Aurora del Palmar', 'Equipos; Individual;Kids', 'Entre Ríos', 'Colon', 'El Palmar', '2015-06-28 00:00:00.0', 'El Terma Adventure Race se traslada el imponente paisaje de las Palmeras Yatay, en uno de los lugares más exóticos de nuestra Mesopotamia: la Reserva Natural de La Aurora del Palmar, próxima al Parque Nacional del mismo nombre, recibirá a los competidores de todo el país en un circuito con todos los atractivos para vivir una hermosa competencia. Un recorrido de 25 km por bañados, cañadones, caminos de arena, senderos en los palmares, campo traviesa, selva en galería y vías del ferrocarril. Consideramos éste el lugar ideal para todos aquellos que quieran hacer su primera experiencia en carreras outdoor, por cuanto se trata de un escenario que permite un pleno disfrute de todo su entorno, rápido, con poco desnivel y una distancia justa para iniciarse en el cross country.     FORMATO: - Equipos: 2 integrantes que deberán participar juntos en el total del recorrido.
    - Individual.
    - Postas: 3 integrantes que efectuarán cada uno de ellos el relevo correspondiente.', 'http://clubdecorredores.com/carreras/aventura/625/Terma-Adventure-Race/', false, 'http://clubdecorredores.com/carreras/2015/c454/logo.jpg', '3/25')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(160, 'Carrera Dexter-Cemic', 'Individual', 'Buenos Aires', 'Vicente López', 'Vito Dumas y Roca', '2015-06-28 00:00:00.0', 'Una Carrera contra el cáncer.  Todo lo recaudado por la inscripción a esta carrera será destinado 
a concretar dicho objetivo.

¡Juntos podemos llegar más lejos!', 'http://clubdecorredores.com/carreras/calle/638/Carrera-Dexter-Cemic/2521/', true, 'http://clubdecorredores.com/carreras/2015/c450/logo.jpg', '2/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(161, 'Pio Run', 'Individual', 'Capital Federal', 'Capital Federal', 'Bosques de Palermo', '2015-07-12 00:00:00.0', 'Con cada inscripción CEPA donará un pollo a una Organización de bien público y regalará otro pollo a cada corredor.', 'http://clubdecorredores.com/carreras/calle/649/Pio-Run/', false, 'http://clubdecorredores.com/carreras/2015/c459/logo.jpg', '10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(162, 'Runner Fest', 'Individual;Kids', 'Capital Federal', 'Capital Federal', 'Pampa & Alcorta', '2015-08-08 00:00:00.0', 'La Runnerfest es la carrera mas divertida y rápida del calendario. La consigna es llevar un juguete para donar por el Día del Niño. El día de la carrera te pones el dorsal, el chip, las zapatillas, para hacer lo que mas te gusta: Correr! Y gracias a tu solidaridad, el juguete que vos donas, se transforma en el Mejor Premio, la Sonrisa mas hermosa de un chico :) .', 'http://www.runnerfest.com/2015/', true, 'http://clubdecorredores.com/carreras/2015/c460/logo.jpg', '1/7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(163, 'Terma Adventure Race - Pinamar', 'Equipos; Individual', 'Buenos Aires', 'Pinamar', '', '2015-08-16 00:00:00.0', '', 'http://clubdecorredores.com/carreras/aventura/626/Terma-Adventure-Race/', false, 'http://clubdecorredores.com/carreras/2015/c454/logo.jpg', '25')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(164, 'Maratón UB', 'Individual;Kids', 'Capital Federal', 'Capital Federal', 'Campo Argentino de Polo', '2015-08-23 00:00:00.0', 'Corramos X el planeta', 'http://clubdecorredores.com/carreras/calle/651/Marat-n-UB/2552/', false, 'http://clubdecorredores.com/carreras/2015/c320/logo.jpg', '1/4/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(165, 'Dale Vida', 'Individual', 'Buenos Aires', 'Costanera Sur', 'Av.de los Italianos y Macacha Güemes', '2015-08-30 00:00:00.0', 'La vida corre por tus venas. Corré o camina por la vida!', 'http://clubdecorredores.com/carreras/calle/641/Dale-Vida/2544/', true, 'http://clubdecorredores.com/carreras/2015/c319/logo.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(166, 'TNF Endurance Challenge Bariloche', 'Individual', 'Río Negro', 'Bariloche', 'Cerro Catedral', '2015-12-06 00:00:00.0', 'La carrera que se desarrolló en el primer semestre (23 de marzo en San Martín de los Andes) siguió el formato Internacional "The North Face Endurance Challenge" con sus cuatro distancias de 80, 50, 21 y 10 km, y fue parte del calendario anual establecido por
The North Face en distintos países del continente: Chile, Perú, Ecuador, Colombia, Costa Rica y Brasil.
La competencia que se llevará a cabo el próximo 6 de diciembre en Cerro Catedral, San Carlos de Bariloche, "The North Face Challenge" tendrá, en cambio, 3 distancias: 50, 21 y 10 km.', 'http://endurancechallengeargentina.com/', true, 'http://clubdecorredores.com/carreras/2015/c411/logo.jpg', '10/21/50')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(167, '10K San Vicente', 'Individual', 'Buenos Aires', 'San Vicente', 'Av. Sarmiento 39', '2015-06-28 00:00:00.0', 'El 28 de junio de 2015 se realizará la Gran Maratón Solidaria de San Vicente, la misma contará de dos distancias: 10K y 4K. La cita es en el Palacio Municipal de San Vicente (Av. Sarmiento 39) a las 9.00hs. Lo recaudado, será a bneficio de dos refugios de perros y gatos.', 'http://www.elrefucorre.com.ar/', false, 'http://www.elrefucorre.com.ar/banner.png', '4/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(168, '15K New Balance', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Figueroa Alcorta y Av. Sarmiento', '2015-08-02 00:00:00.0', '15K Buenos Aires, junto a New Balance. Con un llano y perfecto recorrido en Palermo, ideal para mejorar tiempos.', 'http://15kbuenosaires.com/', false, 'https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-xpf1/v/t1.0-9/10373983_858089024226646_2051812928636482382_n.jpg?oh=0f650c09c03c2c59351bb6ba715cb8f5&oe=55FF55A5&__gda__=1441331919_44dd1b49d4bb1c40ef5257f4e440cf1d', '15')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(169, 'Media Maraton de Iguazu', 'Individual', 'Misiones', 'Iguazú', 'Parque Nacional Iguazú', '2015-08-29 00:00:00.0', 'El 29 de agosto de 2015 se realizará la Media Maratón de Iguazú, la misma contará de dos distancias: 21K y 10K. La cita es en el Parque Nacional Iguazú a las 10.00hs. Ambos circuitos se realizan sobre una ruta 100% asfaltada', 'http://maratoniguazu.com/corredores/inscripcion/', true, 'http://www.yocorro.com.ar/media/k2/items/cache/4a071c64184f6ed127d1b90fcde1a863_L.jpg', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(170, '21K Lanus', 'Individual;Kids', 'Buenos Aires', 'Lanus', 'Club Lanus', '2015-07-09 00:00:00.0', 'El 9 de julio de 2015 se hará la "XXI Maratón Ciudad de Lanús", en donde en el marco de los festejos por el Centenario del club, se correrá por primera vez la distancia de 21K, la cual se suma a los tradicionales 10K. La entrega de premios será en el Micro Estadio de Lanús, donde habrá numerosos stands y se compartirá con grata camaradería el 3º tiempo junto a todos los corredores y Grupos de Running que nos visitan de los distintos lugares del país.', 'https://eventioz.com.ar/organizers/coordinacion-deportes-amateurs-club-atletico-lanus/events', false, 'http://www.yocorro.com.ar/media/k2/items/cache/3b77d3f73b59742412f393cd0d264b14_L.jpg', '2.5/10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(171, '21K de Buenos Aires', 'Individual', 'Capital Federal', 'Capital Federal', 'Av Libertador y Sarmiento', '2015-09-06 00:00:00.0', 'En este 2015 la Media Maratón de Buenos Aires tendrá un nuevo recorrido, la largada será en Av. Libertador y Sarmiento, el día 6 de septiembre.', 'http://sigmasecurepay.info/events/21k-de-buenos-aires-2015-media-maraton-21km/', true, 'http://www.yocorro.com.ar/media/k2/items/cache/7fb770f34c796f7501d3cf0f0dc39075_L.jpg', '21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(172, '30K Buenos Aires Sur', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Roca y General Paz', '2015-07-26 00:00:00.0', 'El 26 de julio de 2015 se realizará la tercera edición de los 30K Buenos Aires Sur. Como es habitual, la cita es en al Autódromo de la Ciudad de Buenos Aires (Av. Roca y General Paz) a las 8:00hs', 'http://30kbuenosairessur.com/inscripcion/', true, 'http://www.yocorro.com.ar/media/k2/items/cache/58b053c805beeea9e04dde1724076741_L.jpg', '10/30')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(173, '42K Rosario', 'Individual', 'Santa Fe', 'Rosario', 'Monumento Nacional a la Bandera', '2015-06-28 00:00:00.0', 'El Maratón de Rosario, que se ha consolidado como uno de los mejores 42K de latinoamérica, tiene fecha de realización el 28 de Junio de 2015, con largada y llegada en el Monumento Nacional a la Bandera', 'http://www.atletismorosario.com.ar/42k/', true, 'http://www.yocorro.com.ar/media/k2/items/cache/7d0d25bfcaa1421c2931a4f0387462aa_L.jpg', '8/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(176, 'Bimbo Global Energy Race 2015', 'Individual', 'Buenos Aires', 'Vicente López', 'Urquiza y Vito Dumas (el rio)', '2015-09-27 00:00:00.0', 'Primera carrera Global Energy. 22 ciudades en un mismo día, decenas de miles de corredores.
Think global, run local.', 'http://www.globalenergyrace.com/es/home', true, 'http://www.tmxteam.com/content/photos/generated/1/3911_slide.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(177, '10K Lan 2015', 'Individual', 'Capital Federal', 'Capital Federal', '', '2015-10-03 00:00:00.0', 'El que corre, vuela', 'http://www.tmxteam.com/evento/813/lanpass-10k-buenos-aires-cordoba', false, 'http://runfun.net/wp-content/uploads/2015/07/10k-lan-pass-run-fun.jpg', '10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(178, '10K Lan 2015', 'Individual', 'Córdoba', 'Córdoba', '', '2015-11-15 00:00:00.0', 'El que corre, vuela', 'http://www.tmxteam.com/evento/813/lanpass-10k-buenos-aires-cordoba', false, 'http://runfun.net/wp-content/uploads/2015/07/10k-lan-pass-run-fun.jpg', '10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(179, 'McDonald’s 5K Las mujeres corremos 2015', 'Individual', 'Capital Federal', 'Capital Federal', 'Puerto Madero', '2015-10-17 00:00:00.0', 'Vuelve el lugar donde las mujeres corren, vuelve M5K de McDonald''s', 'http://www.tmxteam.com/evento/811/mcdonald%E2%80%99s-5k-las-mujeres-corremos-2015', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11667353_10153449227588536_2550936158791613348_n.png?oh=dfb95ddd93f96d98cf30506b63fdfd0e&oe=5624E04B', '3/5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(180, '21K Mizuno', 'Individual', 'Buenos Aires', 'Vicente López', 'Vito Dumas y Urquiza', '2015-11-01 00:00:00.0', '¿Cómo te sentís para los 21K? El 1 de noviembre Mizuno Argentina HalfMarathon te espera para verte llegar con una sonrisa y un objetivo cumplido.', 'http://www.tmxteam.com/evento/inscripcion/808/21k-mizuno-half-marathon-2015', true, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/11063723_10153443764258536_5549737938062275343_n.jpg?oh=b0a82950b291634f089e5326f9978dd4&oe=56203112', '21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(181, 'Disney Magic Run', 'Individual', 'Capital Federal', 'Capital Federal', 'Puerto Madero', '2015-11-22 00:00:00.0', 'Disney Magic Run…aca nadie corre solo', 'http://www.tmxteam.com/disneymagicrun2014/', true, 'http://www.tmxteam.com/disneymagicrun2014/img/background.jpg', '1/3/7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(182, '21K Eco Cross Estancia San Juan', 'Equipos; Individual;Kids', 'Buenos Aires', 'Berazategui', 'Estancia San Juan', '2015-04-12 00:00:00.0', '', 'http://ranelagh7k.com.ar/atletas/wp-atletas/?page_id=53', false, 'http://ranelagh7k.com.ar/atletas/wp-atletas/wp-content/uploads/2014/01/21kflyer.png', '1/7/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(183, 'Casita del Niño Lourdes', 'Individual;Kids', 'Buenos Aires', 'Berazategui', 'Centro Integral Casa del Niño Lourdes', '2015-05-03 00:00:00.0', '', 'http://ranelagh7k.com.ar/atletas/wp-atletas/?page_id=282', false, 'http://ranelagh7k.com.ar/atletas/wp-atletas/wp-content/themes/parabola/images/carreras/perfil_c004.png', '1/3/6')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(184, 'Eco Salud 2015', 'Individual;Kids', 'Buenos Aires', 'Lomas de Zamora', 'Sociedad Alemana de Gimnasia Almirante Brown', '2015-07-25 00:00:00.0', 'El Opds Desarrollo Sostenible invita a la comunidad a participar de la Segunda edición de ECO SALUD a realizarse en esta oportunidad en el partido de Almirante Brown el día Sábado 25 de Julio de 2015, con dos distancias: 4K y 10K. Horario de largada: 16hs. Tambien tiene modalidad Kids, luego de la carrera principal', 'http://ranelagh7k.com.ar/atletas/wp-atletas/wp-content/uploads/2015/07/ecosalud-BANNER-2015-curv.jpg', false, 'http://ranelagh7k.com.ar/atletas/wp-atletas/?page_id=859', '1/4/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(185, 'Maratón de Mar del Plata', 'Individual', 'Buenos Aires', 'Mar del Plata', 'Casino', '2015-11-29 00:00:00.0', 'El próximo 29 de noviembre de 2015 se realizará la 26º Maratón de Mar del Plata. La misma, como es su costumbre, constará de tres distancias: 42K, 21K y 10K. Las distancias 42K y 21K largarán a las 7.10hs, en tanto que la distancia promocional de 10K lo hará a las 8.00hs.', 'https://eventioz.com.ar/e/maraton-mar-del-plata-2015', true, 'http://www.yocorro.com.ar/media/k2/items/cache/8b072d4f47fa16702f8c7356d2c88ee8_XL.jpg', '10/21/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(186, 'Maraton ASI', 'Equipos; Individual;Kids', 'Buenos Aires', 'Caseros', 'Lisandro Medina 2250', '2015-09-13 00:00:00.0', 'Maraton ASI es una carrera de calle organizada por ASI - Osepjana y el Sanatorio Modelo de Caseros con el lema "Corremos por mas Salud"', 'http://www.maratonasi.com.ar/sitio/', false, 'http://www.maratonasi.com.ar/sitio/images/entrada-01.jpg', '1/3/5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(187, 'Maratón Córdoba', 'Individual;Kids', 'Córdoba', 'Ciudad de Córdoba', 'Patio Olmos', '2015-05-03 00:00:00.0', 'En Mayo del 2015 la Ciudad de Córdoba está preparando una gran recepción a los Atletas que participarán en la “Maratón Córdoba”. La ciudad cuenta con hermosos parques, iglesias, el casco histórico, la costanera, la Cañada, el Estadio Kempes; todos ellos incluidos en el recorrido de la “Maratón Córdoba”. La propuesta es una Maratón de Música y Tecnología, representada esta última por los entretenimientos en la Expo, juegos interactivos, transmisión en vivo de la largada y llegada, y puestos de autoconsulta del tiempo inmediatamente al arribo a la meta. La música será dispuesta a lo largo del recorrido de la “Maratón Córdoba”, con veinte grupos musicales que acompañarán a los corredores y al público que seguirá el evento.', 'http://maratondecordoba.com.ar/w/class/42k/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xft1/v/t1.0-9/10645149_1515271518754550_4742285474871287121_n.png?oh=7be7f679c6a606981d25ff0357ba157a&oe=564629CE', '3/10/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(188, 'Media Maraton del Glaciar', 'Individual', 'Santa Cruz', 'El Calafate', 'Parque Nacional Los Glaciares', '2015-04-11 00:00:00.0', 'La Media Maratón del Glaciar, es un evento del tipo deportivo en la modalidad Pedestrismo o Running. Participarán del evento deportistas amateurs y profesionales de diferentes regiones argentinas y de otros países, motivados por el hecho de correr en un lugar de tan alto reconocimiento turístico, como es el Parque Nacional los Glaciares. Las modalidades de 21K y 10K formarán parte de este evento que tiene como principal desafío transitar al aire libre por este único y espectacular paisaje. La totalidad de ambos recorridos se realiza sobre el asfalto.', 'http://maratondelglaciar.com/', false, 'https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-9/10931456_779309118771077_4356585760588004843_n.jpg?oh=3f38f84d8636baf9773628e5f515b810&oe=565AC86C&__gda__=1448595802_4167bb3aafdeb4f8e584adc15edc2e22', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(189, 'Llao Llao 21k', 'Individual', 'Río Negro', 'Bariloche', 'Hotel Llao Llao', '2015-12-19 00:00:00.0', 'Llao Llao 21K, prueba atlética en las modalidades Media Maratón 21K y prueba de 10K. se desarrolla íntegramente dentro del Parque Municipal Llao Llao. El punto de partida y llegada será el predio del Hotel Llao Llao, y recorrerá la ruta en dirección hacía Bahía López, desde donde se realiza el retorno primero para la modalidad 10K. El recorrido de 21K continúa por la ruta, íntegramente por el asfalto, hasta cruzar el arroyo López y se retorna desde el desvío de ripio hacía Colonia Suiza, sobre la misma ruta. El recorrido presenta desniveles moderados.', 'www.llaollao21k.com', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xtf1/v/t1.0-9/10426741_878112785546993_4167136009246866939_n.jpg?oh=d4d0e99912c5f058fb3e54e60e477898&oe=5646B1F0', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(190, '1° Vuelta PARQUE LELOIR', 'Individual', 'Buenos Aires', 'Ituzaingo', 'Sociedad de Fomento La Tradicion, julian Balbin 4020', '2015-08-16 00:00:00.0', 'En colaboración de la ONU y la Sociedad de Fomento "La Tradición" de Ituzaingo. Creamos el evento, la 1° edición de la Vuelta Parque Leloir 8k Competitivos y 3k Participativos. Se realizará a través de la naturaleza del Parque una única vuelta de 8 km y otra de 3. Recorriendo y respirando la Naturaleza de ituzaingó.', 'https://www.facebook.com/events/108836662788427/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11694794_886719354734764_5666350639820223513_n.jpg?oh=81ea7d37be2e763834af4c685276dc1c&oe=5653FC9B', '3/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(191, 'I Maratón Solidaria Familias Abiertas', 'Individual;Kids', 'Buenos Aires', 'Bella Vista', 'Av. Francia y Sourdeaux', '2015-08-23 00:00:00.0', 'Sumate a este evento solidario de ayuda a la niñez', 'http://onlinerun.com.ar/evento/maraton-familias-abiertas/', false, 'http://onlinerun.com.ar/wp-content/uploads/2015/06/AVISO-I-MARAT+%C3%B4N-FAMILIAS-ABIERTAS1-e1435591596282.jpg', '1/7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(192, 'La vuelta de El Palomar', 'Individual', 'Buenos Aires', 'Haedo', 'Av. Rosales 719', '2015-09-20 00:00:00.0', 'A Beneficio del Hospital Posadas nuevamente estaremos realizando la edición de LA VUELTA DE EL PALOMAR (8k y 3k) la cual realizaremos el 20 de Septiembre a las 9 hs. Desde la Av. Rosales frente al Salón de Spinning LINE. Consta de una única vuelta de 8 km y una de 3 km', 'https://www.facebook.com/events/111787652492138/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/1609878_878719418868091_4787093271858092070_n.jpg?oh=8f1f896027091369adbbd70e41da1064&oe=564F1861', '3/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(193, '21k Puente Rosario-Victoria', 'Individual', 'Santa Fe', 'Rosario', 'Puente Rosario Victoria, cabecera lado Rosario', '2015-09-27 00:00:00.0', 'Va a ser hermoso hacer un puente, de verdad, todo para vos!', 'http://www.maratondelpuente.com.ar/', false, 'http://www.maratondelpuente.com.ar/wp-content/uploads/2015/07/mprv15-logo-chico.png', '11/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(194, 'Hi-tec 7 Lagos', 'Equipos;Individual', 'Neuquen', 'Villa La Angostura', '', '2015-09-27 00:00:00.0', 'Es una nueva forma de correr compartiendo con amigos y conocidos en un lugar único de la Patagonia. La Ruta de los 7 Lagos.
100K donde todos los equipos tratarán de hacer el trayecto en el menor tiempo posible. La carrera está programada para que todos los integrantes del equipo puedan disfrutar la Ruta de los 7 Lagos. En partes la harán corriendo, en otras con sus amigos/compañeros en auto parando en los maravillosos paisajes que ofrecen estos 100K.
Los equipos estarán compuestos por 5 integrantes divididos en Categorías PRO y AMATEUR. La Categoría PRO recorrerá 100K con 10 postas de entre 8 y 12 km (2 postas por corredor). La Categoría Amateur recorrerá 50K en 5 postas de entre 8 y 12 km (1 posta por corredor)', 'http://hi-tec7lagos.com/', false, 'http://hi-tec7lagos.com/images/hitec_logo_7lagos.png', '20/50/100')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(195, 'Atlantica Ultramaraton', 'Individual', 'Buenos Aires', 'Pinamar', '', '2015-10-04 00:00:00.0', 'Atlántica Ultramaratón es una prueba única, en un lugar único. Correr junto al mar es una de las experiencias más extraordinarias que se pueden disfrutar sin importar la distancia. La energía de su constante movimiento se siente en medio de su majestuosa inmensidad. La oportunidad de transitar un escenario natural único, agreste y nuestro, una ultra diferente a todas y en un terreno y condiciones sin igual: un nuevo desafío a superar para los corredores de todo el mundo!', 'http://atlanticaultramaraton.com/', false, 'http://argentinarun.com.ar/wp-content/uploads/2015/04/22409_802790913143510_7571832486173706937_n.jpg', '8/30/87/100/120')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(196, '21K La Plata', 'Individual', 'Buenos Aires', 'La Plata', 'Plaza Moreno', '2015-10-04 00:00:00.0', '', 'http://www.21klp.com/', false, 'https://sportick.com.ar/sis/images/header_lmm.jpg', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(197, 'Media Maraton Canota-Villavicencio', 'Individual', 'Mendoza', 'Villavicencio', '', '2015-10-04 00:00:00.0', 'Participen de una de las carreras más bellas que tiene Mendoza por sus paisajes, sus montañas, su fauna y su desafiante circuito que es en constante ascenso hasta llegar a los 1950 mts sobre el nivel del mar.', 'https://www.facebook.com/events/1614109105503195/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/10367164_10207117631608538_3675712882153332210_n.jpg?oh=0eff5e024a3969a58529fcb866289955&oe=5619DCB7', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(198, '8k Nocturna Buenos Aires', 'Individual', 'Capital Federal', 'Capital Federal', '', '2015-10-17 00:00:00.0', 'Viví una nueva edición de la mítica 8K Nocturna Buenos Aires 2015 con muchas sorpresas.', 'http://sportsfacilities.com.ar/v2/evento/nocturna-buenos-aires-2015/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2014/12/AMEXt_1024x470.jpg', '8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(199, 'Media Maraton Sidecreer', 'Individual', 'Entre Ríos', 'Parana', 'Predio del Puerto Viejo', '2015-11-14 00:00:00.0', '', 'http://maratonsidecreer.com.ar/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/1558505_621107397973036_1309023380399408661_n.jpg?oh=3873a13b61ebc5cf4503913c13f7a656&oe=56456E85', '5/10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(200, 'K21 Series Junin', 'Individual', 'Buenos Aires', 'Junin', 'Parque Natural Laguna de Gómez', '2015-07-12 00:00:00.0', 'Con largada y llegada en el Parque Natural Laguna de Gómez, esta etapa nos lleva al principal atractivo turístico lacustre de Buenos Aires, con un entorno que comprende alrededor de 200 ha mayormente arbolada. Con las características de las etapas bonaerenses, se trata de un circuito ligero, de cross, con partes de costering, atravesando bañados y montes de vegetación autóctona.', 'http://k21series.com/junin/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(201, 'K21 Series San Juan', 'Individual', 'San Juan', 'San Juan', 'Punta Tabasco, Dique Ullum', '2015-07-26 00:00:00.0', 'A orillas del Dique Ullun, en medio de una región predominantemente árida, como un oasis aparece la represa de aguas azules, apenas 18 km distante de la ciudad de San Juan. Carrera preponderantemente técnica, con ascenso a cerros que permiten una panorámica de todo el entorno, incluso del valle de Tulúm. El recorrido los llevará con largada y llegada en Punta Tabasco, por el perilago del embalse.', 'http://k21series.com/san-juan/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(202, 'K21 Series Parana', 'Individual', 'Entre Ríos', 'Parana', '', '2015-08-02 00:00:00.0', 'La capital de Entre Ríos será nuevamente sede de la etapa mesopotámica de K21, con un suelo de carácter ondulado, resavio de las cuchillas correntinas, no posee lagos pero sin embargo está bañada por las aguas de río Paraná y Uruguay. Siguiendo el tópico de las etapas de la región pampeana, se trata de un trazado que permite correr prácticamente todo el tiempo , siendo los mayores obstáculos los bañados y zonas que suelen invadirse por el agua, a la vez que posee una vegetación exuberante propia de un clima subtropical. La accesibilidad, los atractivos para pasar un día de disfrute en familia la hacen una excelente propuesta.', 'http://k21series.com/parana/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(203, 'K21 Series La Cumbrecita', 'Individual', 'Córdoba', 'La Cumbrecita', 'Puente Peatonal de La Cumbrecita', '2015-08-22 00:00:00.0', 'Una cálida villa de estilo europeo, enclavada en la zona de sierras cordobesas que reúne todas las bondades de esta región. Buen clima, terreno con variedad de posibilidades, trepadas y descensos técnicos, visuales maravillosas, tupidos bosques de coníferas. La permanente vigilancia del vuelo de los cóndores, hacen de esta una de las etapas más elegidas por los amantes del trail run que buscan la contención de una auténtica aldea de montaña, junto a un desafío a las propias condiciones.', 'http://k21series.com/la-cumbrecita/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(229, 'Armenia Corre', 'Individual', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-10-04 00:00:00.0', 'Nueva edición de Armenia Corre. En este 2015, Armenia Vive, en memoria y reclamo 1915 – 2015. ¡Somos Armenia!', 'http://armeniacorre.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/04/900X900.png', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(204, 'K21 Series Villa Pehuenia', 'Individual', 'Neuquen', 'Villa Pehuenia', 'Frente a Biblioteca Maestro Galeano', '2015-08-30 00:00:00.0', 'La etapa Villa Pehuenia, nos viene premiando con su manto de nieve blanquísima en un 60 % del recorrido por cerros, con las aguas cristalinas de los lagos Moquehue y Aluminé. Joven villa de montaña, contenida por bosques milenarios de araucarias, se llena de magia y magestuoso atractivo. La tercera edición en tierras neuquinas fortaleciendo el contacto con la naturaleza en su estado más puro.', 'http://k21series.com/villa-pehuenia/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(205, 'K21 Series Avellaneda', 'Individual', 'Santa Fe', 'Avellaneda', '', '2015-09-19 00:00:00.0', 'Novedad en el circuito 2014, a 5 km de Reconquista, con senderos marcados por los bañados y sector literalmente invadidos por la vegetación, Avellaneda será nuevamente referencia en el noreste santafecino. Si bien la altimetría no es un factor para nada determinante, los obstáculos naturales, completan la verdadera esencia del espíritu de kseries.', 'http://k21series.com/avellaneda/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(206, 'K21 Series San Rafael', 'Individual', 'San Rafael', 'Mendoza', '', '2015-09-27 00:00:00.0', 'Sexta oportunidad en que K21 llega al Cuyo, y como es ya un clásico a la ciudad de San Rafael, que está rodeada de oportunidades para redescubrir senderos y paisajes propicios para el desafío. San Rafael, una vez más, como referente de las disciplinas que elevan la adrenalina, los espera.', 'http://k21series.com/san-rafael/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(207, 'K21 Series San Pedro', 'Individual', 'Buenos Aires', 'San Pedro', '', '2015-10-03 00:00:00.0', 'Nueva edición de K21 San Pedro, en el bonito entorno de las barrancas del río Paraná, divertido circuito por senderos que se internan el monte, caminos costeros y paisaje campestre. Concentrando la actividad en un predio que contextualiza lo que seguramente será una jornada de compartir con los corredores y acompañantes.', 'http://k21series.com/san-pedro/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(208, 'K21 Series San Martin de los Andes', 'Individual', 'Neuquen', 'San Martin de los Andes', 'El Desafío Mountain Resort, Ruta 40 – S.M. de los Andes', '2015-10-11 00:00:00.0', 'Primavera en la cordillera, y que mejor marco que San Martín de los Andes, en un circuito que combina las bondades de la naturaleza, los andes como contexto, bosques de coníferas, caminos que ascienden a las mejores visuales. Ha sido hasta ahora una perlita dentro del circuito, con algunas novedades en el recorrido que seguirán sumando atractivos.', 'http://k21series.com/san-martin-de-los-andes/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(209, 'K21 Series Lujan', 'Individual', 'Buenos Aires', 'Lujan', '', '2015-10-17 00:00:00.0', 'Atravesada por el río Lujan, la ciudad de la fe, es reconocida mundialmente por la imponente Basílica gótica. Rodeada de estancias y lugares que se prestan al descanso y al contacto con una naturaleza que da el marco adecuado para una nueva etapa de K21. Su trazado contemplará tocar los puntos más característicos de esta maravillosa ciudad, deporte y turismo cultural serán la clave del encuentro.', 'http://k21series.com/lujan/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(210, 'K21 Series Mar del Plata', 'Individual', 'Buenos Aires', 'Mar del Plata', 'Balneario 15, Apolo de Punta Mogotes', '2015-03-01 00:00:00.0', 'La perla del atlántico afianza la etapa de mar, rescatando los puntos turísticos más reconocidos, K21 suma a su favor, tramos de carrera por playa y médanos; sectores ligeros que los llevarán a internarse literalmente en el mar, en el espigón que regala la visual del puerto. Un circuito con la dureza que da la arena combinando kilómetros ágiles de carrera a campo través. Este año, con la modificación de fecha, se acerca a los últimos vestigios de verano para mantener además la posibilidad de disfrutar de la playa.', 'http://k21series.com/mdq/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(211, 'K21 Series Neuquen', 'Individual', 'Neuquen', 'Neuquen', 'Zona Plaza de las Banderas', '2015-02-22 00:00:00.0', '', 'http://k21series.com/confluencia-neuquen/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(212, 'K21 Series Ischigualasto', 'Individual', 'San Juan', 'Ischigualasto', 'Parque Nacional Ischigualasto', '2015-03-15 00:00:00.0', 'Etapa nueva en la serie, recorre el cordón montañoso del Valle Fértil, donde se sitúa el Parque Nacional Ischigualasto, región árida en la que la erosión labró formas singulares con arenisca de color rojo ladrillo y otros que la naturaleza nos obsequia. Con acantilados de hasta 200 mts de altura, combinada con cañadones y gargantas por donde corren arroyos temporarios. Su espectacular paisaje llevó a denominarlo valle de la luna o paisaje de otro mundo. Sin duda, será una de las estrellas de la edición 2015', 'http://k21series.com/ischigualasto/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(213, 'K21 Series Rosario', 'Individual', 'Santa Fe', 'Rosario', 'Campo Timbo', '2015-03-21 00:00:00.0', 'A 40 km de Rosario, con el atractivo propio del campo santafesino, una etapa por demás instalada en el calendario de los corredores, por su fácil acceso, por tratarse de un circuito entretenido, desarrollado a la vera del río Carcarañá, recorriendo la frondosa vegetación del añoso bosque de eucaliptos colorados y especies autóctonas, un cross rápido por sectores y otro tanto divertido.', 'http://k21series.com/rosario/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(214, 'K21 Series Colon', 'Individual', 'Entre Ríos', 'Colon', 'Desde Cámping “Los Tilos”, camino costero sur S/N.', '2015-04-12 00:00:00.0', 'Correr en las inmediaciones del río Uruguay, su delta, con arroyos y bañados. La vegetación caracterizada por la selva en galería –derivación final de la selva misionera, con lapachos, laurel y seibos; sectores con suelos pantanosos y las cuchillas características hacen de K21 Colon una etapa variada, con el agua como elemento preponderante que se completa recorriendo kilómetros de playas de arena fina .', 'http://k21series.com/colon/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(230, 'Carrera por los Derechos del Niño', 'Individual', 'Buenos Aires', 'Vicente López', '', '2015-10-04 00:00:00.0', 'Correr por los chicos te hace grande, sigamos corriendo juntos. Por los derechos del niño curado del cáncer.', 'http://sportsfacilities.com.ar/v2/evento/por-los-derechos-del-nino/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/07/900x900.png', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(215, 'K21 Series Areco', 'Individual', 'Buenos Aires', 'San Antonio de Areco', 'Parque Criollo', '2015-05-03 00:00:00.0', 'Nuevo destino, a 110 km de Buenos Aires, incursionando en San Antonio de Areco una de las ciudades más antiguas y características del campo argentino. A la vera del río Areco, con un entorno que deslumbra por la calidad de sus producciones artesanales, el santuario Gaucho también ofrecerá completar una jornada de disfrute de naturaleza y gastronomía.', 'http://k21series.com/areco/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(216, 'K21 Series Neuquen', 'Individual', 'Neuquen', 'Villa El Chocon', 'Gimnasio Municipal.', '2015-05-24 00:00:00.0', 'A 80 km de Neuquén Capital, con el Lago Ramos Mexía y un terreno caracterizado por su suelo arcilloso, típico paisaje de la estepa patagónica, el circuito se desarrolla por senderos que atraviesan la meseta, bordeando el río Limay con la permanente panorámica del espejo azul del lago. En los suelos desérticos que caracterizan el entorno de Villa El Chocon, se encontraron los restos del dinosaurio carnívoro considerado el más grande descubierto, que 100 millones de años atrás, recorría la región. Esta será la segunda oportunidad de desandar sus senderos, K21 EL CHOCON, inicio de la edición 2015 de la Copa Optitech K21 Salomon, les da la bienvenida!', 'http://k21series.com/neuquen/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(217, 'K21 Series San Nicolas', 'Individual', 'Buenos Aires', 'San Nicolas', 'Parque Rafael de Aguiar', '2015-05-31 00:00:00.0', 'Mística y natural podríamos definir a la etapa de San Nicolás, circuito pleno de paisajes cautivantes, a orillas del río Paraná, ideal para integrar el costering, internarse en los cañaverales y divertirse en los montes de vegetación autóctona, las infaltables barrancas completan una propuesta que se consolida.', 'http://k21series.com/san-nicolas/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(218, 'K21 Series San Lorenzo', 'Individual', 'Salta', 'San Lorenzo', 'El Fortín calle Mariano Moreno al pie del cerro', '2015-06-14 00:00:00.0', 'Sosteniendo el recorrido elegido en el 2014, se busca seguir mostrando los mejores atractivos de la zona teniendo unas excelentes vistas de San Lorenzo, tanto del Este como del Oeste, mostrando sus distintas vegetaciones, las Yungas, la imponente y frondosa avenida de acceso y como su nombre lo dice la famosa Loma Balcón y cambiando el lugar de Largada y llegada a los 1.438 m.s.n.m. se busca ubicarse con una muy linda vista al pie del cerro y hacer una carrera más DURA y un poco más lerda que la anterior, los que participen de la opción de 21 Km en sus últimos kilómetros tendrán que llegar a los 1.996 m.s.n.m. y los de 11 Km tendrán su altura máxima en la llegada.', 'http://k21series.com/san-lorenzo/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(219, 'K21 Series Tandil', 'Individual', 'Buenos Aires', 'Tandil', 'Polideportivo Municipal y Espacio Espiritual Huella Mapuche', '2015-06-21 00:00:00.0', 'Tan sólo su nombre representa un ícono de la actividad al aire libre, los encantos de esta región tan accesible desde las grandes urbes, con una historia deportiva incuestionable, con todos los aditamentos para ser la vedete de la serie. Su trazado lleva a transitar las sierras más antiguas del planeta, los atractivos turísticos de una ciudad preparada para la aventura, garantizando los elementos indispensables de una gran prueba de cross country.', 'http://k21series.com/tandil/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/10920903_620768081288774_1091139458042730843_n.jpg?oh=db78896385392b3628f5d8b750d1c2e5&oe=56575807', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(220, '4º Desafio del Colorado – TRAIL RUN', 'Individual', 'La Pampa', 'La Adela', '', '2015-08-23 00:00:00.0', '', 'http://www.aventurasdelacomark.com.ar/calendario-trail-run-2015/4o-desafio-del-colorado-trail-run/', false, 'http://www.aventurasdelacomark.com.ar/wp-content/uploads/2015/02/Trail-Running1.jpg', '7/14/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(221, 'Trail del Viento', 'Individual', 'Neuquen', 'Chos Malal', '', '2015-10-30 00:00:00.0', 'TRAIL DEL VIENTO es un evento que reta al espíritu de los corredores a través del deporte al aire libre, y el trail running.
El Norte Neuquino y la Cordillera del Viento nos invitan a vivir una gran aventura participando en una de las 4 pruebas que les proponemos. Esta carrera será por senderos de montaña, huellas, rastros o caminos, todo alrededor de un tipo de  montaña diferente... LA CORDILLERA QUE NO CONOCES!
Recorrerán la Cordillera del Viento en las distancias de 10km, 20 km y 50 km, la carrera mas técnica y rigurosa de las tres pruebas. Correran en vertical sobre el Cerro Mayal, un gigante de oro. Mientras, experimentaremos una  belleza natural impresionante y la cultura de la región.
TRAIL DEL VIENTO es el resultado de un sueño de personas que se han criado en este maravilloso entorno y de otras que se han enamorado con solo conocer el lugar.', 'http://www.traildelviento.com/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xat1/v/t1.0-9/11108832_1630122843899694_1473780458270982780_n.jpg?oh=9195c14f9bf1a228babf08ec3d6e9bac&oe=564DFA94', '10/20/50')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(222, 'Gendarmeria Nacional', 'Individual', 'Buenos Aires', 'Costanera Sur', 'Av. de los italianos y Manuela Saenz', '2015-08-16 00:00:00.0', '', 'http://10kgendarmerianacional.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/06/Flyer.png', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(223, 'Dog Run Buenos Aires', 'Con Perro', 'Capital Federal', 'Capital Federal', 'Figueroa Alcorta y Monroe', '2015-08-30 00:00:00.0', 'DOGRUN es un evento deportivo donde perros y dueños corren o caminan juntos, comparten actividad física, amistad y vida saludable.', 'http://dogrun.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/06/PLACA-CENTRAL-WEB-SF-1024X470.png', '1/3/5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(224, 'Dog Run Rosario', 'Con Perro', 'Santa Fe', 'Rosario', 'Parque Independencia', '2015-10-04 00:00:00.0', 'DOGRUN es un evento deportivo donde perros y dueños corren o caminan juntos, comparten actividad física, amistad y vida saludable.', 'http://dogrun.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/06/PLACA-CENTRAL-WEB-SF-1024X470.png', '1/3/5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(225, 'Maraton Assist Card', 'Equipos', 'Buenos Aires', 'Vicente López', '', '2015-09-13 00:00:00.0', '', 'http://sportsfacilities.com.ar/v2/evento/maraton-assistcard/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/07/900x900-3.png', '')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(226, 'Circuito de Estaciones Primavera', 'Individual', 'Capital Federal', 'Capital Federal', 'Puerto Madero', '2015-09-27 00:00:00.0', '', 'http://www.circuitoestaciones.com.ar/2015/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/01/Pieza_General_900x900.png', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(227, 'Circuito de Estaciones Invierno', 'Individual', 'Capital Federal', 'Capital Federal', 'Av. Figueroa Alcorta y Sarmiento (Palermo)', '2015-07-09 00:00:00.0', 'La etapa Otoño fue un éxito total, Invierno promete incluso superarla. El próximo 9 de julio se corre en Palermo la segunda parada del Circuito de las Estaciones 2015, competencia con de distancias de 5K y 10K, que cuenta con el patronicio principal de William Hope.', 'http://www.circuitoestaciones.com.ar/2015/', false, 'http://adm.atletas.info/upload/evento/215/img_banner_evento.jpg', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(228, 'Circuito de Estaciones Otoño', 'Individual', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-05-10 00:00:00.0', '', 'http://www.circuitoestaciones.com.ar/2015/', false, 'http://adm.atletas.info/upload/evento/214/img_banner_evento.jpg', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(231, 'Halloween Run', 'Individual', 'Buenos Aires', 'Vicente López', '', '2015-10-31 00:00:00.0', 'Por primera vez, llega Halloween Run el 31 de Octubre. ¿Estás preparado para desafiar tus miedos?', 'http://sportsfacilities.com.ar/v2/evento/halloween-run/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/06/900-x-900_31.png', '')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(232, '5K Racing Club', 'Individual', 'Capital Federal', 'Capital Federal', '', '2015-11-08 00:00:00.0', 'El 8 de Noviembre 2015 “la academia” vuelve a vivir su gran fiesta con sus 5K Racing Club.', 'http://sportsfacilities.com.ar/v2/evento/racing-club/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/01/racing_1024-x-470-2015.jpg', '5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(233, 'Circuito de Estaciones Verano', 'Individual', 'Capital Federal', 'Capital Federal', '', '2015-12-06 00:00:00.0', '', 'http://www.circuitoestaciones.com.ar/2015/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/05/Cover_Facebook_850x315.jpg', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(234, 'San Silvestre', 'Individual', 'Capital Federal', 'Capital Federal', '', '2015-12-31 00:00:00.0', 'Única e inolvidable, 6° edición del clasico porteño, los 8K San Silvestre Buenos Aires vuelve a largar el 31 de Diciembre', 'http://sansilvestrebuenosaires.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/01/FLYER_1024-x-470_san-sil-01.jpg', '8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(235, 'Reynado 10K', 'Individual', 'Buenos Aires', 'Castelar', 'Avenida Pres. Domingo F. Sarmiento 3391', '2015-06-28 00:00:00.0', '', 'http://www.eventosrunners.com.ar/reynado-10k/', false, 'https://scontent-gru1-1.xx.fbcdn.net/hphotos-xat1/v/t1.0-9/11196238_1583386921934491_7804174631642175370_n.jpg?oh=d8baaf8b3517f841f75340efb61be1a7&oe=5616A55C', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(236, 'San Martin Corre 8K', 'Individual', 'Buenos Aires', 'San Martin', 'Parque Yrigoyen', '2015-06-07 00:00:00.0', 'Parte de lo recaudado se destinará al programa de Rotary Chau Polio.', 'http://maratonsanmartin.com.ar/', false, 'https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-xap1/v/t1.0-9/11082641_454977097987476_8199964904333900893_n.jpg?oh=6d5fe36db1e5f4de63b9dcf21c5a9c67&oe=561A9394&__gda__=1447314760_1a3cbffebc4039ce00d0663055447d40', '1/4/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(237, 'UM Corre', 'Individual', 'Buenos Aires', 'Moron', 'Cabildo y Machado', '2015-04-26 00:00:00.0', '', 'http://www.umcorre.com/', false, 'https://scontent-gru1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/17298_947995618552040_4349667623628306062_n.jpg?oh=6287a0f33b9a9af710f4a3da5405e66b&oe=5619CA15', '1/3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(238, 'Haedo Corre', 'Individual', 'Buenos Aires', 'Haedo', 'Las Bases 221', '2015-08-30 00:00:00.0', '', 'http://www.ateneogym.com.ar/actividades.html', false, 'http://www.ateneogym.com.ar/info_actividades/maraton15/x.jpg', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(239, 'Tus 15K', 'Individual;Kids', 'Buenos Aires', 'Costanera Sur', '', '2015-07-26 00:00:00.0', '', 'http://onlinerun.com.ar/evento/tus-15km/', false, 'http://onlinerun.com.ar/wp-content/uploads/2015/04/Logo-Onlinerun-e1430155995891.jpg', '1/15')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(240, 'Gesell Corre de Noche', 'Individual;Kids', 'Buenos Aires', 'Villa Gesell', 'Club de Playa Eliseo (', '2015-01-24 00:00:00.0', '', 'http://gesellcorredenoche.com.ar/web/', false, 'https://scontent-gru1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10509661_306491382859392_8628573307428052952_n.jpg?oh=21879c100acd43b7bdacf7be71b9cf3b&oe=560EC6B9', '1/3/6')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(241, '8K Brisas', 'Individual', 'Buenos Aires', 'Haedo', '', '2015-07-09 00:00:00.0', '', 'https://www.facebook.com/maraton.brisas', false, 'https://scontent-gru1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/11168561_461505347331890_3394782208177062236_n.jpg?oh=e63a1aacbec82eaf4cc55a313a2d7a84&oe=56469BE8', '4/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(242, 'General Rodriguez Corre', 'Individual', 'Buenos Aires', 'General Rodriguez', 'Av. 25 de Mayo e Int. Manny', '2015-05-10 00:00:00.0', '', 'http://onlinerun.com.ar/evento/rodriguez-corre2015/', false, 'http://www.generalrodriguez.gov.ar/images/nota/1225-corre1.jpg', '3/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(243, '3er CrossCountry Canning', 'Individual;Kids', 'Buenos Aires', 'Canning', 'Complejo Recreativo Veselka', '2015-05-31 00:00:00.0', '', 'http://circuitodeatletas.com.ar/', false, 'http://runfun.net/wp-content/uploads/2015/04/Captura-de-pantalla-2015-04-09-a-las-23.41.49-e1428633955123.png', '1/5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(244, 'Maratón "Por más Derechos y más Igualdad"', 'Individual;Kids', 'Buenos Aires', 'Ituzaingo', 'Plaza 20 de Febrero', '2015-03-09 00:00:00.0', 'El Consejo de Mujeres de Ituzaingó por la Igualdad de Género realizará la tercera edición de la Maratón “Por más Derechos y más Igualdad” el domingo 8 de marzo a partir de las 9 hs en el marco del Día Internacional de la Mujer, con el objetivo de concientizar y profundizar las políticas de género llevadas adelante por el Consejo.', 'http://onlinerun.com.ar/evento/maraton-2015/', false, 'http://www.miituzaingo.gov.ar/images_Noticias/maraton.JPG', '1/3/5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(245, 'Maraton 8K General Rodriguez', 'Individual', 'Buenos Aires', 'General Rodriguez', '', '2015-03-08 00:00:00.0', 'Pongamos fin a la polio', 'http://rotary8km.blogspot.com.ar/', false, 'https://scontent-gru1-1.xx.fbcdn.net/hphotos-xft1/v/t1.0-9/11001860_920127311338871_3192479749010091560_n.jpg?oh=d42ee66411d042aa44bae25687276a5d&oe=5659BF65', '4/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(246, 'Women Night Run', 'Individual', 'Buenos Aires', 'Vicente López', 'Paseo de la Costa y Guemes', '2015-03-28 00:00:00.0', 'En la Women Night Run, la noche es de ellas. 5K + Show Nocturno en Vicente Lopez', 'http://womennightrun.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/02/1024-x-4701.jpg', '5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(247, 'Media Maraton Mendoza', 'Individual', 'Mendoza', 'Mendoza', '', '2015-03-22 00:00:00.0', 'Primera edición de la Media Maratón de la Ciudad de Mendoza 2015, con 21K y 10K. Deja tu huella.', 'http://www.mediamaratondemendoza.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2014/12/banner736-x-736-02.jpg', '10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(248, '5K Alcohol Cero al Volante', 'Individual', 'Buenos Aires', 'Pinamar', '', '2015-01-18 00:00:00.0', 'Una nueva edición de los 5K de Seguridad Vial y el Ministerio del Interior y Transporte. ¡Gratuita!', 'http://www.5kmlametaesllegar.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2014/12/736pina.jpg', '5')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(249, 'Maraton de Mendoza', 'Individual', 'Mendoza', 'Mendoza', 'Los Portones, Parque General San Martin', '2015-05-02 00:00:00.0', '16° edición de la Maratón Internacional de Mendoza (MIM), con 42K, 21K y 10K', 'http://www.maratondemendoza.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2014/12/FB-Patrocinio-Maraton-Mendoza1.png', '10/21/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(250, 'Media de B''aires', 'Individual', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-04-12 00:00:00.0', 'La Media de B’Aires es conocida como la más encantadora de Latinoamérica. Distancia de 21K', 'http://21ksudamericano.ativo.com/mediadebaires//', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/01/post_ads.jpg', '21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(251, '7ma Caminata Urbana', 'Individual', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-04-11 00:00:00.0', 'El 11 de Abril camina con tu familia en los bosques de Palermo, junto al Hospital Italiano. ¡Gratuita!', 'http://www.caminatahospitalitaliano.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/02/Banner-web-1024x470-pxOK.jpg', '3')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(252, 'Corre Pa Catamarca', 'Individual', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-06-28 00:00:00.0', 'El 28 de Junio de 2015 Buenos Aires Corre Pa Catamarca, con 10K y 3K Participativos.', 'http://sportsfacilities.com.ar/v2/evento/corre-pa-catamarca/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/05/900x900_1.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(253, 'Grupos LT', 'Individual;Kids', 'Capital Federal', 'Capital Federal', 'Palermo', '2015-06-14 00:00:00.0', 'Un clásico de todos los inviernos, competí junto a los Grupos LT el 14 de Junio de 2015.', 'http://lacarreragruposlt.com/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/01/1024-X-470-c-sponsors2.jpg', '1/3/7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(254, 'Carrera Ciudad Verde', 'Individual', 'Capital Federal', 'Capital Federal', 'Plaza de Mayo', '2015-05-17 00:00:00.0', 'Dos grupos que parten de un mismo lugar, y llegan a lugares diferentes. Reciclables y Orgánicos.', 'http://carreraciudadverde.com.ar/', false, 'http://sportsfacilities.com.ar/v2/wp-content/uploads/2015/04/Slider-sitio_61.jpg', '4')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(255, 'XV Vuelta de Hurlingham', 'Individual', 'Buenos Aires', 'Hurlingham', 'Av. Pedro Diaz 1710', '2015-09-27 00:00:00.0', '', 'https://eventioz.com.ar/e/xv-vuelta-de-hurlingham', false, 'http://www.deporteshurlingham.com.ar/version2/images/flyeremergente.jpg', '4/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(256, 'Lujan Late por el Hospice', 'Individual;Kids', 'Buenos Aires', 'Lujan', 'Av. Ntra. Señora de Luján y 25 de mayo', '2015-09-13 00:00:00.0', 'Todo lo recaudado será a completo beneficio del Hospice Madre Teresa, una ONG lujanense que brinda cuidados paliativos de forma gratuita a personas que padecen una enfermedad progresiva e incurable como el cáncer y que necesitan de dicha modalidad de atención.', 'https://eventioz.com.ar/e/lujan-late-por-el-hospice', true, 'http://hospicemadreteresa.org.ar/lujanlate/wp-content/uploads/2015/07/lujanlate-hero.png', '1/3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(257, 'Maratón Capilla Racing Club 2015', 'Individual', 'Buenos Aires', 'Exaltación de la Cruz', '25 de Mayo Norte, 500', '2015-09-13 00:00:00.0', '', 'https://eventioz.com.ar/e/maraton-capilla-racing-club-2015--2', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11705110_1003578116340171_8742033683712610621_n.jpg?oh=77651379db15d922536a2d0d2ff4a053&oe=564E969F', '4/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(258, 'Trail Runner 10K AVENTURA', 'Individual', 'Santa Fe', 'Reconquista', 'Club Hipico Reconquista', '2015-08-22 00:00:00.0', '', 'https://eventioz.com.ar/e/trail-runner-10k-aventura', false, 'https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-9/11692527_941278735895163_6219106216225505335_n.jpg?oh=2efee43c86760edc4e430fca1c5e333c&oe=5657B040&__gda__=1443757686_463e05d4fcf04e51fb464918bdbce5e9', '10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(259, '10K de A.D.U.M.', 'Individual;Kids', 'Buenos Aires', 'Mar del Plata', 'Plaza España', '2015-08-17 00:00:00.0', '', 'https://eventioz.com.ar/e/13-edicion-carrera-10-k-adum', false, 'https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xpt1/v/t1.0-9/11695816_942016555862293_6401513021438445140_n.jpg?oh=800b45bc3662368f034ae18efee67eb5&oe=5657F67A&__gda__=1444194174_437bd675d94591069031467ca496a62a', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(260, 'Cross del Parque Lomas', 'Individual', 'Buenos Aires', 'Lomas de Zamora', 'Molina Arrotea, 2200', '2015-08-16 00:00:00.0', '', 'https://eventioz.com.ar/e/cross-del-parque-lomas-agosto-2015--2', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/1014416_600746656666555_485617235_n.png?oh=b4c57fc08cf461672a3959ffb1bdc1ce&oe=5619CFAA', '1.5/5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(261, '15K Open Sports Adventure 2015', 'Equipos;Individual', 'Buenos Aires', 'Mar del Plata', 'Laguna de los Padres', '2015-08-02 00:00:00.0', 'El Domingo 02 de Agosto se llevará a cabo la 2º Etapa del Circuito 15K Open Sports – 3º Edición - en Laguna de los Padres de la ciudad de Mar del Plata.', 'http://www.inscribiteonline.com.ar/verEvento.php?evento=8207#toShow', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11051747_942877542442861_7613202758540218579_n.jpg?oh=b293165346bf4aa7c9970bb74bf8d34c&oe=565858BA', '5/15')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(262, 'Festival Atlético Día del Niño', 'Individual;Kids', 'Buenos Aires', 'Miramar', 'Av. 40 y Calle 13', '2015-08-02 00:00:00.0', 'Festival Dia del Niño. En el sindicato de T Municipales, desde las 9.00 hs se inscriben con un alimento no perecedero.', 'https://www.facebook.com/pages/Agrupaci%C3%B3n-Atl%C3%A9tica-General-Alvarado/164097970304406', false, 'https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xpt1/v/t1.0-9/11703363_874067905974072_5955572375427282680_n.jpg?oh=4fa36839d6953eb9cb3720cb62d3b21e&oe=565418DC&__gda__=1444483288_5ca38b8d28977953a4e017d4da943a9f', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(263, '10K de Fasta', 'Individual', 'Buenos Aires', 'Mar del Plata', 'Plaza España', '2015-09-26 00:00:00.0', 'Lo recaudado será donado en su totalidad para el sostenimiento de las obras de FASTA en África.', 'http://www.10kilometrosdefasta.com/', false, 'http://nebula.wsimg.com/0bf5d9199844b87af8374a8bbaef17f3?AccessKeyId=69DF9E3C45694B99F6B7&disposition=0&alloworigin=1', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(264, 'Yaboty Ultra Maraton', 'Individual', 'Misiones', 'El Soberbio', 'Yaboty', '2015-09-19 00:00:00.0', 'Yaboty ultra maraton es la mayor ultramaratón de selva del mundo. Se corre en plena selva misionera y en 2015 será su quinta edición consecutiva, con una convocatoria mayor de mil corredores de todo el pais y el mundo. Las distancias posibles son: 10k , 26k, 42k,70k ó 100k (no importa que distancia elijas correr, será solo el primer paso!).', 'http://salvaje.com.ar/evento/informacion/59', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xtf1/v/t1.0-9/11745711_942104892520126_1742396607586594710_n.jpg?oh=e7caec012dd55ca1aee90702ee42eade&oe=5659C1C5', '12/26/42/70/100')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(265, 'Tour Canteras', 'Individual', 'Buenos Aires', 'Mar del Plata', 'El Encanto Km. 8,5 - Ruta 88, Batan', '2015-09-13 00:00:00.0', 'Es hora de superar distancias 21K - 9K y 3 km. Un remodelado recorrido bajo el mismo marco, inmensas canteras, quintas, vías, sendas y pendientes, ya está en marcha el CLASICO de Crosscountry.', 'http://www.rumbo135.com.ar/interna.php?id=13', false, 'https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xpf1/v/t1.0-9/11011600_942104855853463_2636493827299937866_n.jpg?oh=d5d3aa0f9dc0d45d12ebafe3e3e36cfa&oe=565A8AEC&__gda__=1448566150_a60805d462c369c4fe7a76bcc3492962', '3/9/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(266, '8K Tranquera Abierta', 'Individual;Kids', 'Buenos Aires', 'Otamendi', '', '2015-09-06 00:00:00.0', 'Te ofrecemos pasar un día distinto, en familia, en un entorno distinto y que te lleves el premio mas valioso para todo atleta.', 'https://www.facebook.com/catletismootamendi', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/11692565_841015765995180_7330706505783002532_n.jpg?oh=80df67dc0979a78c7ba9393496029321&oe=560E8564', '3.5/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(267, 'Desafío Avanza 2015', 'Equipos; Individual;Kids', 'Buenos Aires', 'Miramar', 'Polideportivo Municipal de Miramar', '2015-07-26 00:00:00.0', '', 'http://heyevent.com/event/fy6o26s2w4xw2a/desafio-avanza-miramar', false, 'https://scontent.xx.fbcdn.net/hphotos-xfa1/t31.0-8/s720x720/11155174_1577224752565413_5820851846534671779_o.jpg', '1/4/8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(268, '8° Maraton Solidaria', 'Individual', 'Buenos Aires', 'Maipu', 'Plaza San Martín', '2015-09-20 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/maraton%20maipu/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/maraton%20maipu/afiche.jpg', '3/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(269, 'NightRun Laguna', 'Individual', 'Buenos Aires', 'Mar del Plata', 'Laguna de los Padres', '2015-05-09 00:00:00.0', '', 'http://www.rumbo135.com.ar/eventos_pasados.php', false, 'http://yocorroyvos.com.ar/nightrun_laguna2015/buho%20(500x251).jpg', '8')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(270, 'NightRun Mar del Plata', 'Individual', 'Buenos Aires', 'Mar del Plata', 'Banquina Puerto Mar del Plata', '2015-01-31 00:00:00.0', '', 'http://www.rumbo135.com.ar/eventos_pasados.php?id=24', false, 'http://www.rumbo135.com.ar/img_secciones/night_run_mdp_2015.jpg', '9')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(271, 'NightRun Pinamar', 'Individual', 'Buenos Aires', 'Pinamar', '', '2015-01-17 00:00:00.0', '', 'http://www.rumbo135.com.ar/eventos_pasados.php?id=23', false, 'http://www.rumbo135.com.ar/img_secciones/night_run_pinamar_2015.jpg', '7')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(272, 'Napa Corre de Noche 15k', 'Equipos;Individual', 'Buenos Aires', 'Napaleofú', '', '2015-12-06 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/napa-corre-de-noche/ficha_tecnica.htm', false, 'https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xtf1/v/t1.0-9/11188402_481006742052230_7798960948459226487_n.jpg?oh=e52cb4b272b144b8d0d9161f2faa89ee&oe=564B36B6&__gda__=1447848173_d71b5aec77aca4b39f4315d850ba2a74', '8/15')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(273, 'Finisterra Corre', 'Equipos; Individual;Kids', 'Buenos Aires', 'Sierra de los Padres', '', '2015-10-11 00:00:00.0', 'Carrera de Aventura, modalidad off road / cross-country, con una distancias aproximadas de 5k, 10K, 30k y postas de 30k x 3 integrantes de 10k cada uno, kids y de integración.', 'http://www.finisterra.org.ar/', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/finisterra/afiche.jpg', '5/10/30')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(274, 'Travesia del Sudeste (Orense/Claromecó)', 'Equipos;Individual', 'Buenos Aires', 'Tres Arroyos', 'Claromecó', '2015-10-11 00:00:00.0', 'Travesía del Sudeste, es una carrera original y novedosa de aventura de largo aliento uniendo los Balnearios Orense y Claromecó, por las extensas playas que posee el Partido de Tres Arroyos. La distancia a recorrer es de 28 Km por arena, partiendo desde la bajada de Orense, atravesando los diferentes saltos de piedra, dunas y lagunas hasta llegar a las playas de Claromecó. Dicha prueba contemplará para su participación diferentes categorías: individual (masculino y femenino), en parejas (masculino, femenino y mixto) y en postas por duplas y tercetos (masculino, femeninos y mixto).', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/travesia_del_sudeste/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/travesia_del_sudeste/afiche.jpg', '28')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(275, '10K Parque La Hormiga', 'Individual', 'Buenos Aires', 'Olavarría', 'Parque La Hormiga en Sierra Chica', '2015-07-19 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/cavo_parque%20hormiga/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/cavo_parque%20hormiga/afiche.jpg', '5/10')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(276, 'Monte Corre "La Aventura"', 'Individual', 'Buenos Aires', 'Monte Hermoso', 'Paseo del Pinar', '2015-07-26 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/montecorre_laaventura/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/montecorre_laaventura/afiche.jpg', '5/10/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(277, '10ma Edición Media Maraton de Quequen', 'Individual', 'Buenos Aires', 'Necochea', 'Predio de la Universidad', '2015-08-02 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/mediamaraton_quequen/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/mediamaraton_quequen/afiche2.jpg', '2.5/5/21')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(278, 'Vuelta a la Laguna de Chascomus', 'Equipos;Individual', 'Buenos Aires', 'Chascomus', '', '2015-08-23 00:00:00.0', '', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/leiman_vuelta-chascomus/ficha_tecnica.htm', false, 'http://www.codigoaventura.com.ar/codigoaventura/carreras/leiman_vuelta-chascomus/afiche.jpg', '30')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(279, 'Tandil Ultra Trail 2015', 'Individual', 'Buenos Aires', 'Tandil', 'Posta Natural - Zona "La Elena"', '2015-08-23 00:00:00.0', 'El frío de Agosto te traerá la oportunidad de "CORRER TUS LIMITES" en el TANDIL ULTRA TRAIL 2015. Esta será una prueba de cross trail a tu medida en las sierras más antiguas del planeta, que se encuentran en Tandil, provincia de Buenos Aires. Las pendientes permanentes en los caminos y sendas serranas serán las constantes del trayecto que te llevará por los lugares más destacados de nuestro entorno. Esta prueba, llamada a convertirse en un clásico del trail, te propone tres diferentes distancias: 11k, 30k y 50k que te permitirán elegir el desafío a tu medida. Con la salida del sol del 23 de Agosto se iniciará la segunda edición de una competencia que pondrá a prueba tus límites. ¿Sos capaz de correrlos?', 'http://www.perfilextremo.com/ultratrail.html', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/18791_1056894550988668_1561016540801809766_n.jpg?oh=5096d6171ac040b5fb16c3d1145512e3&oe=5654F32C', '11/30/50')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(280, '1er. Desafío Río Quequén Salado', 'Individual', 'Buenos Aires', 'Tres Arroyos', 'Paraje “Paraje Puente Viejo” camino Copetonas/Oriente', '2015-09-13 00:00:00.0', 'El próximo 13 de Setiembre se desarrollará la primera carrera de aventura sobre las márgenes del río Quequén Salado. Un lugar maravilloso para el running aventura. Serán 8 K y 15 K atravesando campos, canteras y acumulando desniveles por las altas barrancas a orillas del río.', 'http://www.codigoaventura.com.ar/codigoaventura/carreras/Desafio%20quequen%20salado/ficha_tecnica.htm#inscripcion', false, 'https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-xft1/v/t1.0-9/11424435_1645053209046249_5606145324967959777_n.jpg?oh=70482bfcde1f8cea6691c06cea8bde60&oe=565B7B30&__gda__=1447382865_6bfe773bd5229adfb93c145eeb03a3cd', '8/15')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(281, 'M42. Maraton de Montaña Villa Ventana', 'Individual;Kids', 'Buenos Aires', 'Villa Ventana', '', '2015-05-31 00:00:00.0', 'M42 es una carrera con una variedad de paisajes increíbles, con un importante desnivel. Nuclea a gente de una variedad de destinos importantes.', 'http://crossdeaventura.com.ar/', false, 'https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xpf1/v/t1.0-9/21703_669025419869017_6147130225695418314_n.jpg?oh=6e3b9ca5ee61f916386945792be1de4b&oe=56534FFC&__gda__=1444429079_6dfcf8046ccba4355daa15589fafdd99', '10/25/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(282, 'M42. Maraton de Montaña Sa. de los Padres', 'Individual;Kids', 'Buenos Aires', 'Sierra de los Padres', '', '2015-09-27 00:00:00.0', 'M42 es una carrera con una variedad de paisajes increíbles, con un importante desnivel. Nuclea a gente de una variedad de destinos importantes.', 'http://crossdeaventura.com.ar/', false, 'https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/11755850_696061353832090_2247889875625306169_n.jpg?oh=b8fd44d860ffbf51e3889a29f668dea7&oe=5613FC84', '10/25/42')
GO
INSERT INTO public.carrera(id, nombre, modalidades, provincia, ciudad, direccion, fecha_inicio, descripcion, url_web, recomendada, url_imagen, distancia_disponible)
  VALUES(283, 'Maraton Solidaria Mariano Forgit', 'Individual', 'Buenos Aires', 'Mar de Ajo', 'Estanislao del Campo y Espora', '2015-09-13 00:00:00.0', 'Se realiza en Mar de Ajo el 13 de Septiembre la 5ta Edición MARATÓN SOLIDARIA MARIANO FORGIT, piloto de la Fuerza Aérea falleciendo en un accidente aéreo realizando maniobras de vuelo. 
Para los que no saben Mariano era el Hermano de Pablo Forgit.
Esperamos poder contar con la presencia de uds apoyando este evento solidario y la familia que desde hace 5 años están aprendiendo a vivir con lo sucedido, poniendo todo de si, para que este evento, crezca año a año.
NO IMPORTA SI CORRES O CAMINAS, SOLO PENSA EN QUE PODES AYUDAR A ALGUIEN CON TU PRESENCIA.
INSCRIPCIÓN: ALIMENTO NO PERECEDERO que será donado a comedores infantiles de Mar de Ajo y el Partido de la Costa', 'https://eventioz.com.ar/e/maraton-solidaria-mariano-forgit-2015', true, 'https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xtp1/v/t1.0-9/11694761_746054542187863_4799943215344960480_n.jpg?oh=4f7c5bdd96945425664e39975213f525&oe=56153007&__gda__=1447648561_1728d6abb86e09276d5f84764bf867b2', '1/4/10')
GO
